In [35]:
import pandas as pd, numpy as np
from db_queries import get_location_metadata as get_locs

In [36]:
# tier1_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/nigeria_ethiopia_india_coverage_data.csv'

In [37]:
ls /ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/ | grep tier

~$gday_data_assumptions_tier2.xlsx
gday_data_assumptions_tier2.xlsx
gday_tier2_03_16_2021.csv
gday_tier3_03_23_2021.csv
gday_tier4_03_29_2021.csv
population_coverage_data_tier2_input_data.csv
population_coverage_data_tier2_locs_3_17_2021.csv
population_coverage_data_tier3_locs_3_23_2021.csv
population_coverage_data_tier3_locs_3_26_2021.csv
population_coverage_data_tier3_locs_3_31_2021.csv
population_coverage_data_tier4_locs_3_26_2021.csv
population_coverage_tier3_input_data.csv
tier1234_coverage_data_2021_03_24.csv
tier123_coverage_data_2021_03_24.csv
tier1_coverage_data_03_31_2021.csv
tier5_coverage_data_03_29_2021.csv

In [49]:
tier1_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/tier1_coverage_data_03_31_2021.csv'
tier2_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/population_coverage_data_tier2_locs_3_17_2021.csv'
tier3_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/population_coverage_data_tier3_locs_3_31_2021.csv'
tier4_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/population_coverage_data_tier4_locs_3_26_2021.csv'
tier5_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/tier5_coverage_data_03_29_2021.csv'

In [50]:
t1 = pd.read_csv(tier1_path)
t2 = pd.read_csv(tier2_path)
t3 = pd.read_csv(tier3_path)
t4 = pd.read_csv(tier4_path)
t5 = pd.read_csv(tier5_path)

In [51]:
all_data = pd.concat([t1, t2, t3, t4, t5])

/ihme/homes/beatrixh/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [52]:
all_data = all_data.drop(columns='location_id')

# sort_helper = {
#     'percent of population eating fortified vehicle': 'C',
#  'percent of population eating industrially produced vehicle': 'B',
#  'percent of population eating vehicle': 'A'}


# all_data['sort_helper'] = all_data.value_description.map(sort_helper)

# all_data = all_data.sort_values(['location_name','vehicle','sort_helper','value_description','nutrient']).drop(columns='sort_helper')

# col_order = ['location_name','vehicle','value_description','nutrient','value_mean','value_025_percentile','value_975_percentile','sub_population','estimation_status', 'source_citation',
#        'source_link', 'data_choice_notes', 'CI_source']

# all_data = all_data[col_order]

In [53]:
all_data

,CI_source,data_choice_notes,estimation_status,location_name,nutrient,source_citation,source_link,sub_population,value_025_percentile,value_975_percentile,value_description,value_mean,vehicle
0,modeling,NaN,regression,Ethiopia,na,NaN,NaN,NaN,37.969140,80.550510,percent of population eating vehicle,59.259825,maize flour
1,modeling,NaN,regression,Ethiopia,na,NaN,NaN,NaN,17.408327,36.931299,percent of population eating industrially prod...,27.169813,maize flour
2,modeling,NaN,regression,Ethiopia,folic acid,NaN,NaN,NaN,0.000000,0.000000,percent of population eating fortified vehicle,0.000000,maize flour
3,modeling,NaN,regression,Ethiopia,iron,NaN,NaN,NaN,0.000000,0.000000,percent of population eating fortified vehicle,0.000000,maize flour
4,modeling,NaN,regression,Ethiopia,vitamin a,NaN,NaN,NaN,0.000000,0.000000,percent of population eating fortified vehicle,0.000000,maize flour
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,modeling,NaN,regression,Sudan,na,NaN,NaN,NaN,NaN,NaN,percent of population eating industrially prod...,35.365713,wheat flour
96,modeling,NaN,regression,Sudan,folic acid,NaN,NaN,NaN,NaN,NaN,percent of population eating fortified vehicle,1.760469,wheat flour
97,modeling,NaN,regression,Sudan,iron,NaN,NaN,NaN,NaN,NaN,percent of population eating fortified vehicle,1.760469,wheat flour
98,modeling,NaN,regression,Sudan,vitamin a,NaN,NaN,NaN,NaN,NaN,percent of population eating fortified vehicle,1.760469,wheat flour
99,modeling,NaN,regression,Sudan,zinc,NaN,NaN,NaN,NaN,NaN,percent of population eating fortified vehicle,1.760469,wheat flour

In [54]:
final_cols = ['location_id', 'location_name', 'sub_population', 'vehicle',
       'value_description', 'nutrient', 'value_mean', 'value_025_percentile',
       'value_975_percentile']

In [55]:
loc_metadata = get_locs(location_set_id=35, gbd_round_id=6, decomp_step="step4")

In [56]:
loc_metadata = loc_metadata.loc[loc_metadata.location_name.isin(all_data.location_name.unique()),['location_id','location_name']]

In [60]:
loc_metadata = loc_metadata[loc_metadata.location_id!=25344]

In [61]:
all_data = all_data.merge(loc_metadata, on = 'location_name', how = 'left')

In [62]:
df = all_data.copy()#[final_cols + ['estimation_status']]

In [63]:
df.head()

,CI_source,data_choice_notes,estimation_status,location_name,nutrient,source_citation,source_link,sub_population,value_025_percentile,value_975_percentile,value_description,value_mean,vehicle,location_id
0,modeling,NaN,regression,Ethiopia,na,NaN,NaN,NaN,37.969140,80.550510,percent of population eating vehicle,59.259825,maize flour,179
1,modeling,NaN,regression,Ethiopia,na,NaN,NaN,NaN,17.408327,36.931299,percent of population eating industrially prod...,27.169813,maize flour,179
2,modeling,NaN,regression,Ethiopia,folic acid,NaN,NaN,NaN,0.000000,0.000000,percent of population eating fortified vehicle,0.000000,maize flour,179
3,modeling,NaN,regression,Ethiopia,iron,NaN,NaN,NaN,0.000000,0.000000,percent of population eating fortified vehicle,0.000000,maize flour,179
4,modeling,NaN,regression,Ethiopia,vitamin a,NaN,NaN,NaN,0.000000,0.000000,percent of population eating fortified vehicle,0.000000,maize flour,179

In [64]:
# df.to_csv(all_inputted_data_path, index = False)

In [65]:
df.sub_population.unique()

array([nan, 'under-5', 'women of reproductive age', '0-24 months',
       'total population', '8-59 months', 'children 12-36 months',
       'households with children <2 years old'], dtype=object)

In [66]:
subpop_map = {
    'total population': 'total population',
    'women of reproductive age': 'women of reproductive age',
    'under-5': 'under-5',
    '8-59 months': 'under-5',
    'children 12-36 months': 'under-5',
    'households with children <2 years old': 'NA',
    '0-24 months':'under-5',
    np.nan : 'NA'
}

df['subpop_val'] = df.sub_population.map(subpop_map)

In [67]:
df.subpop_val.unique()

array(['NA', 'under-5', 'women of reproductive age', 'total population'],
      dtype=object)

In [68]:
df['nq_counts'] = df.groupby(['location_name','vehicle','value_description','nutrient']).transform('count').subpop_val

In [69]:
df[(df.nq_counts > 1)].sort_values(['location_name','vehicle','value_description','nutrient']).set_index(['location_id','location_name','vehicle','value_description','nutrient'])[['nq_counts','subpop_val','value_mean','value_025_percentile','value_975_percentile']]

                                                                                                   nq_counts  \
location_id location_name vehicle     value_description                                  nutrient
161         Bangladesh    wheat flour percent of population eating vehicle               na                2
                                                                                         na                2
201         Burkina Faso  wheat flour percent of population eating vehicle               na                2
                                                                                         na                2
202         Cameroon      wheat flour percent of population eating vehicle               na                2
                                                                                         na                2
179         Ethiopia      oil         percent of population eating industrially produ... na                2
                                                                                         na                2
                          wheat flour percent of population eating industrially produ... na                2
                                                                                         na                2
20          Viet Nam      oil         percent of population eating vehicle               na                2
                                                                                         na                2
                          wheat flour percent of population eating vehicle               na                2
                                                                                         na                2

                                                                                                                  subpop_val  \
location_id location_name vehicle     value_description                                  nutrient
161         Bangladesh    wheat flour percent of population eating vehicle               na        women of reproductive age
                                                                                         na                          under-5
201         Burkina Faso  wheat flour percent of population eating vehicle               na        women of reproductive age
                                                                                         na                          under-5
202         Cameroon      wheat flour percent of population eating vehicle               na        women of reproductive age
                                                                                         na                          under-5
179         Ethiopia      oil         percent of population eating industrially produ... na                          under-5
                                                                                         na        women of reproductive age
                          wheat flour percent of population eating industrially produ... na                          under-5
                                                                                         na        women of reproductive age
20          Viet Nam      oil         percent of population eating vehicle               na                          under-5
                                                                                         na                               NA
                          wheat flour percent of population eating vehicle               na        women of reproductive age
                                                                                         na                          under-5

                                                                                                   value_mean  \
location_id location_name vehicle     value_description                                  nutrient
161         Bangladesh    wheat flour percent of population eating vehicle               na              41.9
                                                                                         na              76.2
201         Burkina Faso  wheat flour percent of population eating vehicle               na              48.0
                                                                                         na              57.0
202         Cameroon      wheat flour percent of population eating vehicle               na              92.0
                                                                                         na              94.0
179         Ethiopia      oil         percent of population eating industrially produ... na              70.0
                                                                                         na              50.0
                          wheat flour percent of population eating industrially produ... na              27.0
                                                                                         na              20.0
20          Viet Nam      oil         percent of population eating vehicle               na              38.3
                                                                                         na              56.3
                          wheat flour percent of population eating vehicle               na              38.8
                                                                                         na              16.4

                                                                                                   value_025_percentile  \
location_id location_name vehicle     value_description                                  nutrient
161         Bangladesh    wheat flour percent of population eating vehicle               na                   31.257526
                                                                                         na                   56.845429
201         Burkina Faso  wheat flour percent of population eating vehicle               na                   21.097889
                                                                                         na                   25.053743
202         Cameroon      wheat flour percent of population eating vehicle               na                   90.000000
                                                                                         na                   92.000000
179         Ethiopia      oil         percent of population eating industrially produ... na                   64.070691
                                                                                         na                   45.764779
                          wheat flour percent of population eating industrially produ... na                   23.210993
                                                                                         na                   17.193328
20          Viet Nam      oil         percent of population eating vehicle               na                   19.140406
                                                                                         na                    0.000000
                          wheat flour percent of population eating vehicle               na                   17.054127
                                                                                         na                    7.208445

                                                                                                   value_975_percentile
location_id location_name vehicle     value_description                                  nutrient
161         Bangladesh    wheat flour percent of population eating vehicle               na                   52.542474
                                                                                         na                   95.554571
201         Burkina Faso  wheat flour percent of population eating vehicle               na                   74.902111
                                                                                         na                   88.946257
202         Cameroon      wheat flour percent of population eating vehicle               na                   94.000000
                                                                                         na                   96.000000
179         Ethiopia      oil         percent of population eating industrially produ... na                   75.929309
                                                                                         na                   54.235221
                          wheat flour percent of population eating industrially produ... na                   30.789007
                                                                                         na                   22.806672
20          Viet Nam      oil         percent of population eating vehicle               na                   57.459594
                                                                                         na                  100.000000
                          wheat flour percent of population eating vehicle               na                   60.545873
                                                                                         na                   25.591555

In [70]:
assert(df.nq_counts.min()==1), "data formatting error"

In [71]:
df['u5_applicable'] = False
df['wra_applicable'] = False

df.loc[(df.nq_counts==1),'u5_applicable'] = True
df.loc[(df.nq_counts==1),'wra_applicable'] = True

In [72]:
df.loc[(df.nq_counts==2) &
       (df.subpop_val=='under-5'),
       'u5_applicable'] = True

df.loc[(df.nq_counts==2) &
       (df.subpop_val=='women of reproductive age'),
       'wra_applicable'] = True

In [73]:
#what's left over?
df.loc[(df.nq_counts==2) &
       ~(df.subpop_val.isin(['under-5','women of reproductive age']))]

,CI_source,data_choice_notes,estimation_status,location_name,nutrient,source_citation,source_link,sub_population,value_025_percentile,value_975_percentile,value_description,value_mean,vehicle,location_id,subpop_val,nq_counts,u5_applicable,wra_applicable
155,modeling,NaN,regression,Viet Nam,na,NaN,NaN,NaN,0.0,100.0,percent of population eating vehicle,56.3,oil,20,NA,2,False,False

In [74]:
df.loc[(df.location_name=="Viet Nam") & (df.vehicle=="oil") & (df.value_description=="percent of population eating vehicle")]

,CI_source,data_choice_notes,estimation_status,location_name,nutrient,source_citation,source_link,sub_population,value_025_percentile,value_975_percentile,value_description,value_mean,vehicle,location_id,subpop_val,nq_counts,u5_applicable,wra_applicable
154,modeling,Only one source. Used value for all under-5 (3...,na,Viet Nam,na,"Laillou, A. et al. “An Assessment of the Impac...",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3...,under-5,19.140406,57.459594,percent of population eating vehicle,38.3,oil,20,under-5,2,True,False
155,modeling,NaN,regression,Viet Nam,na,NaN,NaN,NaN,0.000000,100.000000,percent of population eating vehicle,56.3,oil,20,NA,2,False,False

In [75]:
df.loc[(df.nq_counts==2) &
       ~(df.subpop_val.isin(['under-5','women of reproductive age'])),'wra_applicable'] = True

In [76]:
df[(df.wra_applicable)].shape, df[(df.u5_applicable)].shape

((328, 18), (328, 18))

In [77]:
df[final_cols + ['u5_applicable','wra_applicable']]

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
0,179,Ethiopia,NaN,maize flour,percent of population eating vehicle,na,59.259825,37.969140,80.550510,True,True
1,179,Ethiopia,NaN,maize flour,percent of population eating industrially prod...,na,27.169813,17.408327,36.931299,True,True
2,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.000000,0.000000,0.000000,True,True
3,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,iron,0.000000,0.000000,0.000000,True,True
4,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.000000,0.000000,0.000000,True,True
...,...,...,...,...,...,...,...,...,...,...,...
330,522,Sudan,NaN,wheat flour,percent of population eating industrially prod...,na,35.365713,NaN,NaN,True,True
331,522,Sudan,NaN,wheat flour,percent of population eating fortified vehicle,folic acid,1.760469,NaN,NaN,True,True
332,522,Sudan,NaN,wheat flour,percent of population eating fortified vehicle,iron,1.760469,NaN,NaN,True,True
333,522,Sudan,NaN,wheat flour,percent of population eating fortified vehicle,vitamin a,1.760469,NaN,NaN,True,True
334,522,Sudan,NaN,wheat flour,percent of population eating fortified vehicle,zinc,1.760469,NaN,NaN,True,True

In [ ]:
df[df.wra_applicable].shape, df[df.wra_applicable]

In [33]:
df[(df.location_name=="Ethiopia") & (df.vehicle=="maize flour")][['location_name','vehicle','value_description','nutrient','value_mean']].sort_values(['location_name','vehicle','value_description','nutrient'])

,location_name,vehicle,value_description,nutrient,value_mean
2,Ethiopia,maize flour,percent of population eating fortified vehicle,folic acid,0.000000
3,Ethiopia,maize flour,percent of population eating fortified vehicle,iron,0.000000
4,Ethiopia,maize flour,percent of population eating fortified vehicle,vitamin a,0.000000
5,Ethiopia,maize flour,percent of population eating fortified vehicle,zinc,0.000000
1,Ethiopia,maize flour,percent of population eating industrially prod...,na,27.169813
0,Ethiopia,maize flour,percent of population eating vehicle,na,59.259825

In [34]:
w_metadata_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/lsff_input_coverage_data_with_metadata.csv'
df[final_cols + ['u5_applicable','wra_applicable','estimation_status','source_citation', 'source_link','CI_source', 'data_choice_notes']].to_csv(w_metadata_path, index = False)

In [35]:
all_inputted_data_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/lsff_input_coverage_data.csv'

In [36]:
df = df.sort_values(['location_name','vehicle','value_description','nutrient'])

In [37]:
df[final_cols + ['u5_applicable','wra_applicable']].to_csv(all_inputted_data_path)

In [38]:
df[final_cols + ['u5_applicable','wra_applicable']].to_csv('/ihme/homes/beatrixh/repos/scratch/lsff_input_coverage_data.csv')