In [1]:
import pandas as pd, numpy as np
from tqdm import tqdm

import data_processing
import lbwsg_boe
import iron_bw_calc_zero
# import lbwsg
# import lsff_interventions
# import demography

!date
!whoami
!pwd

Wed Apr 14 14:04:29 PDT 2021
ndbs
/ihme/homes/ndbs/vivarium_research_lsff/nanosim_models

In [8]:
%load_ext autoreload
%autoreload 2

# Load input data so I can look at it

In [2]:
input_data = data_processing.get_fortification_input_data()
input_data._fields

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

('locations', 'coverage', 'consumption', 'concentration')

In [3]:
input_data.locations

                       location_name  location_id
0                             Angola          168
1                         Bangladesh          161
2                       Burkina Faso          201
3                           Cameroon          202
4                              China            6
5                      Côte d'Ivoire          205
6   Democratic Republic of the Congo          171
7                              Egypt          141
8                           Ethiopia          179
9                              Ghana          207
10                             India          163
11                         Indonesia           11
12                             Kenya          180
13                        Madagascar          181
14                        Mozambique          184
15                           Myanmar           15
16                             Nepal          164
17                             Niger          213
18                           Nigeria          214
19                          Pakistan          165
20                      South Africa          196
21                             Sudan          522
22                            Uganda          190
23       United Republic of Tanzania          189
24                          Viet Nam           20

# First time `main()` with computing both 0% and 100% coverage, and computing the "categorical" PIF as well as the interpolated PIF

It took about 24s for 10,000 simulants and 10 draws. Scaling to 80,000 simulants and 250 draws would take about 4800 s, or 80 minutes.

Note that in the output dataframe, `'coverage_level'` is the proportion of the gap between fortified and fortifiable, so 0% population coverage corresponds to the negative number, and 100% population coverage corresponds to the number that's greater than 1.

In [5]:
%%time
iron_bw_calc_zero.main(
    '/ihme/homes/ndbs/vivarium_research_lsff',
    'temp',
    'Cameroon',
    10_000,
    10,
    random_seed=3456,
    take_mean=False
)

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/tables/atom.py:1224: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return pickle.loads(array.tostring())

CPU times: user 23.5 s, sys: 1.03 s, total: 24.6 s
Wall time: 23.7 s

In [6]:
# Time (in seconds)  needed to scale to 40_000 simulants and 250 draws
(40_000/10_000) * (250/10) * 24

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

2400.0

In [7]:
# Time (in seconds)  needed to scale to 80_000 simulants and 250 draws
(80_000/10_000) * (250/10) * 24

4800.0

I moved the Cameroon output file to `~/temp/` and renamed it "zero_one" to avoid overwriting it on the next test run:

In [9]:
results_cameroon = pd.read_csv('~/temp/iron_bw_results__Cameroon_zero_one.csv')
results_cameroon

,location_id,vehicle,coverage_level,measure,age_group_id,draw_43,draw_67,draw_240,draw_298,draw_314,draw_539,draw_558,draw_709,draw_737,draw_767
0,202,maize flour,-0.954571,pif,2,-0.000165,-0.000759,-0.001059,-0.000212,-0.000288,-0.000141,-0.000233,-0.000332,-0.000081,-0.000190
1,202,maize flour,-0.954571,pif,3,-0.000100,-0.000367,-0.000363,-0.000079,-0.000099,-0.000097,-0.000124,-0.000151,-0.000038,-0.000096
2,202,maize flour,-0.954571,categorical_pif,2,0.000000,0.000000,0.000006,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,202,maize flour,-0.954571,categorical_pif,3,-0.000012,-0.000012,-0.000019,-0.000017,-0.000019,-0.000016,-0.000016,-0.000012,0.000000,-0.000009
4,202,maize flour,-0.954571,averted_dalys,2,-182.198649,-942.341086,-1155.014494,-270.958680,-238.377929,-150.360242,-318.820503,-391.520527,-76.766079,-208.128236
5,202,maize flour,-0.954571,averted_dalys,3,-21.645562,-97.258303,-65.779499,-20.859455,-19.715367,-20.969963,-24.307316,-33.342979,-6.110126,-19.229641
6,202,maize flour,17.196730,pif,2,0.001160,0.004406,0.006685,0.001716,0.002123,0.001272,0.001307,0.002134,0.000548,0.001399
7,202,maize flour,17.196730,pif,3,0.001752,0.006480,0.007915,0.001978,0.002350,0.001886,0.001705,0.002505,0.000627,0.002082
8,202,maize flour,17.196730,categorical_pif,2,0.000133,0.001171,0.001949,0.000092,0.000321,0.000135,0.000190,0.000251,0.000200,0.000194
9,202,maize flour,17.196730,categorical_pif,3,0.000556,0.002456,0.002097,0.000314,0.000894,0.000353,0.001566,0.001012,0.000489,0.000707
10,202,maize flour,17.196730,averted_dalys,2,1246.815723,5748.323126,7006.843818,2261.283228,1924.114801,1438.779506,1780.289946,2525.412655,542.582313,1498.685212
11,202,maize flour,17.196730,averted_dalys,3,397.271332,1739.806311,1434.376388,519.490959,480.088988,419.768563,382.601807,603.564849,101.246339,407.585140
12,202,wheat flour,-2.673767,pif,2,-0.000335,-0.000887,-0.002232,-0.000756,-0.001203,-0.000748,-0.000744,-0.000652,-0.000392,-0.000627
13,202,wheat flour,-2.673767,pif,3,-0.000495,-0.001164,-0.002502,-0.001373,-0.001280,-0.001302,-0.000802,-0.000791,-0.000463,-0.000854
14,202,wheat flour,-2.673767,categorical_pif,2,-0.000032,-0.000213,-0.004784,-0.000319,-0.000434,-0.000417,-0.000259,-0.000462,-0.000021,-0.000296
15,202,wheat flour,-2.673767,categorical_pif,3,-0.000069,-0.000467,-0.001452,-0.000356,-0.002103,-0.000710,-0.000163,-0.000189,-0.000060,-0.000184
16,202,wheat flour,-2.673767,averted_dalys,2,-353.526153,-1186.201868,-2389.989868,-1028.024590,-1116.381502,-865.909225,-1016.935842,-778.011976,-392.136285,-668.639555
17,202,wheat flour,-2.673767,averted_dalys,3,-106.377118,-308.389436,-460.377366,-370.477136,-261.444122,-286.756413,-168.605078,-175.802671,-73.506452,-167.319366
18,202,wheat flour,2.029685,pif,2,0.000668,0.001297,0.001544,0.001427,0.001033,0.000875,0.000585,0.001043,0.000710,0.000569
19,202,wheat flour,2.029685,pif,3,0.000701,0.001032,0.001280,0.001175,0.000632,0.000602,0.000483,0.000668,0.000583,0.000402
20,202,wheat flour,2.029685,categorical_pif,2,0.003029,0.003817,0.001976,0.004655,0.007824,0.000854,0.005418,0.001962,0.000035,0.001697
21,202,wheat flour,2.029685,categorical_pif,3,0.001048,0.001689,0.000910,0.002549,0.001725,0.001199,0.000426,0.000653,0.001175,0.001106
22,202,wheat flour,2.029685,averted_dalys,2,722.474613,1690.468500,1625.298277,1843.506360,926.333899,984.803096,799.780198,1205.818884,695.528938,610.247460
23,202,wheat flour,2.029685,averted_dalys,3,164.791084,279.236017,231.499982,304.993424,138.597909,135.273624,102.687118,160.496696,93.971052,78.047954

In [14]:
input_data.coverage.query(
    "location_name=='Cameroon' and vehicle in ['wheat flour', 'maize flour']"
    " and nutrient in ['iron', 'na'] and wra_applicable==True"
)

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
165,202,Cameroon,NaN,maize flour,percent of population eating vehicle,na,47.295467,19.911581,74.679353,True,True
166,202,Cameroon,NaN,maize flour,percent of population eating industrially prod...,na,11.521177,4.850462,18.191893,True,True
168,202,Cameroon,NaN,maize flour,percent of population eating fortified vehicle,iron,5.135229,2.161952,8.108506,True,True
174,202,Cameroon,women of reproductive age,wheat flour,percent of population eating vehicle,na,92.000000,90.000000,94.000000,False,True
176,202,Cameroon,NaN,wheat flour,percent of population eating industrially prod...,na,75.570909,37.181341,99.999990,True,True
178,202,Cameroon,NaN,wheat flour,percent of population eating fortified vehicle,iron,53.088564,35.980674,70.196453,True,True

# Now time `main()` edited to compute 0% coverage only, and without the categorical PIF

It took about half as long (13s). Let's run just this version since that's all we need. Scaling to 80,000 simulants and 250 draws should take about 2600 s, or 43 minutes.

In [16]:
%%time
iron_bw_calc_zero.main(
    '/ihme/homes/ndbs/vivarium_research_lsff',
    'temp',
    'Cameroon',
    10_000,
    10,
    random_seed=3456,
    take_mean=False
)

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/tables/atom.py:1224: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return pickle.loads(array.tostring())

CPU times: user 12.5 s, sys: 650 ms, total: 13.1 s
Wall time: 13.2 s

In [17]:
# Time (in seconds) needed to scale to 40_000 simulants and 250 draws
(40_000/10_000) * (250/10) * 13

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

1300.0

In [18]:
# Time (in seconds)  needed to scale to 80_000 simulants and 250 draws
(80_000/10_000) * (250/10) * 13

2600.0

In [19]:
# Bytes of memory / (rows of table) = bytes available per row
50e9 / (250*80_000)

2500.0

In [20]:
results_cameroon2 = pd.read_csv('temp/iron_bw_results__Cameroon.csv')
results_cameroon2

,location_id,vehicle,coverage_level,measure,age_group_id,draw_43,draw_67,draw_240,draw_298,draw_314,draw_539,draw_558,draw_709,draw_737,draw_767
0,202,maize flour,-0.954571,pif,2,-0.000077,-0.000307,-0.000343,-0.000087,-0.000090,-0.000050,-0.000074,-0.000101,-0.000019,-0.000048
1,202,maize flour,-0.954571,pif,3,-0.000094,-0.000552,-0.000303,-0.000051,-0.000054,-0.000069,-0.000074,-0.000145,-0.000027,-0.000069
2,202,maize flour,-0.954571,averted_dalys,2,-79.133179,-390.829470,-365.331508,-112.427770,-81.435941,-56.600219,-101.311839,-114.860546,-19.073511,-55.178120
3,202,maize flour,-0.954571,averted_dalys,3,-19.183319,-134.241907,-52.745943,-13.527331,-10.899384,-13.827490,-14.218533,-28.497875,-4.056615,-13.325872
4,202,wheat flour,-2.673767,pif,2,-0.000314,-0.000945,-0.002690,-0.000915,-0.001409,-0.001148,-0.000715,-0.000722,-0.000333,-0.000711
5,202,wheat flour,-2.673767,pif,3,-0.000625,-0.001329,-0.003284,-0.001333,-0.001453,-0.001312,-0.000788,-0.000846,-0.000645,-0.000998
6,202,wheat flour,-2.673767,averted_dalys,2,-323.628378,-1200.474832,-2734.453294,-1186.537346,-1258.278213,-1248.067844,-925.241979,-795.581324,-320.176591,-728.161471
7,202,wheat flour,-2.673767,averted_dalys,3,-149.734213,-375.486908,-613.524841,-360.461838,-342.439513,-301.822851,-197.289273,-220.476075,-109.754641,-200.170554

In [22]:
results_cameroon.query("coverage_level < 0 and measure != 'categorical_pif'")

,location_id,vehicle,coverage_level,measure,age_group_id,draw_43,draw_67,draw_240,draw_298,draw_314,draw_539,draw_558,draw_709,draw_737,draw_767
0,202,maize flour,-0.954571,pif,2,-0.000165,-0.000759,-0.001059,-0.000212,-0.000288,-0.000141,-0.000233,-0.000332,-0.000081,-0.000190
1,202,maize flour,-0.954571,pif,3,-0.000100,-0.000367,-0.000363,-0.000079,-0.000099,-0.000097,-0.000124,-0.000151,-0.000038,-0.000096
4,202,maize flour,-0.954571,averted_dalys,2,-182.198649,-942.341086,-1155.014494,-270.958680,-238.377929,-150.360242,-318.820503,-391.520527,-76.766079,-208.128236
5,202,maize flour,-0.954571,averted_dalys,3,-21.645562,-97.258303,-65.779499,-20.859455,-19.715367,-20.969963,-24.307316,-33.342979,-6.110126,-19.229641
12,202,wheat flour,-2.673767,pif,2,-0.000335,-0.000887,-0.002232,-0.000756,-0.001203,-0.000748,-0.000744,-0.000652,-0.000392,-0.000627
13,202,wheat flour,-2.673767,pif,3,-0.000495,-0.001164,-0.002502,-0.001373,-0.001280,-0.001302,-0.000802,-0.000791,-0.000463,-0.000854
16,202,wheat flour,-2.673767,averted_dalys,2,-353.526153,-1186.201868,-2389.989868,-1028.024590,-1116.381502,-865.909225,-1016.935842,-778.011976,-392.136285,-668.639555
17,202,wheat flour,-2.673767,averted_dalys,3,-106.377118,-308.389436,-460.377366,-370.477136,-261.444122,-286.756413,-168.605078,-175.802671,-73.506452,-167.319366

In [26]:
# Estimated minutes to run
2600/60

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

43.333333333333336

# See if 50GB of memory is enough to run 100,000 simulants and 250 draws, or if this crashes my kernel...

Never mind, it's taking too long to find out. I'll just stick with 80,000 to be safe since I know that worked before.

In [30]:
%%time
iron_bw_calc_zero.main(
    '/ihme/homes/ndbs/vivarium_research_lsff',
    'temp',
    'Bangladesh',
    100_000,
    250,
    random_seed=3456,
    take_mean=False
)

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/tables/atom.py:1224: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return pickle.loads(array.tostring())

KeyboardInterrupt:

In [31]:
pd.read_csv('temp/iron_bw_results__Nigeria.csv')

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,location_id,vehicle,coverage_level,measure,age_group_id,draw_43,draw_67,draw_240,draw_298,draw_314,draw_539,draw_558,draw_709,draw_737,draw_767
0,214,maize flour,-0.298331,pif,2,0.000110,-0.000027,0.000000,0.000000,0.000000,0.000000,0.000000,0.000068,0.000000,0.000000
1,214,maize flour,-0.298331,pif,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,214,maize flour,-0.298331,averted_dalys,2,1568.155596,-934.212856,0.000000,0.000000,0.000000,0.000000,0.000000,1631.212552,0.000000,0.000000
3,214,maize flour,-0.298331,averted_dalys,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,214,wheat flour,-0.376662,pif,2,-0.000012,-0.000015,-0.000025,-0.000023,-0.000015,-0.000011,-0.000014,-0.000014,-0.000009,-0.000015
5,214,wheat flour,-0.376662,pif,3,-0.000308,-0.000234,-0.000298,-0.000324,-0.000104,-0.000265,-0.000292,-0.000433,-0.000154,-0.000268
6,214,wheat flour,-0.376662,averted_dalys,2,-162.404882,-253.895692,-371.919438,-324.651679,-208.061328,-146.112103,-217.175108,-200.816335,-135.856384,-207.201835
7,214,wheat flour,-0.376662,averted_dalys,3,-746.735742,-743.294827,-782.303215,-982.587068,-246.073783,-610.752744,-754.935684,-1171.605806,-433.817535,-674.606077

In [33]:
input_data.locations.location_name.to_list()

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

['Angola',
 'Bangladesh',
 'Burkina Faso',
 'Cameroon',
 'China',
 "Côte d'Ivoire",
 'Democratic Republic of the Congo',
 'Egypt',
 'Ethiopia',
 'Ghana',
 'India',
 'Indonesia',
 'Kenya',
 'Madagascar',
 'Mozambique',
 'Myanmar',
 'Nepal',
 'Niger',
 'Nigeria',
 'Pakistan',
 'South Africa',
 'Sudan',
 'Uganda',
 'United Republic of Tanzania',
 'Viet Nam']

In [34]:
'141'.isdigit()

True

In [35]:
input_data.locations.location_id.to_list()

[168,
 161,
 201,
 202,
 6,
 205,
 171,
 141,
 179,
 207,
 163,
 11,
 180,
 181,
 184,
 15,
 164,
 213,
 214,
 165,
 196,
 522,
 190,
 189,
 20]