In [1]:
import pandas as pd, numpy as np

# Add 'industry {vehicle}' to coverage input data

In [2]:
## pull in (previously final) input data sheet
outputs_dir = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/'
input_data_path = outputs_dir + 'lsff_input_coverage_data.csv'

input_data = pd.read_csv(input_data_path)

loc_id_map = {i:j for(i,j) in zip(input_data.location_name, input_data.location_id) }

In [3]:
# pull in (previously final) version of input data sheet with metadata
w_meta = pd.read_csv(outputs_dir + 'lsff_input_coverage_data_with_metadata.csv')

## wheat

In [4]:
# pull in new numbers from Jonathan / industry
inputs_dir = "/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/inputs/"
new_wheat = pd.read_excel(inputs_dir + "Kopie_von_20210412_LSFF_input_data_for_IHME_(002)_editLeo.xlsx", header = [1,2,3])

In [5]:
# set location index
new_wheat = new_wheat.set_index(new_wheat.columns[0])

In [6]:
# they only asked us to update % fortifiable, but want to check if the % fortified matches us
industry_wheat_fortified = new_wheat['Baseline coverage']['Wheat flour\n(percent of population eating specified wheat flour)']['Wheat flour fortified with iron'].reset_index()
test = input_data.loc[(input_data.vehicle=="wheat flour") & (input_data.u5_applicable) & (input_data.nutrient=="iron"),['location_name','value_mean']]
industry_wheat_fortified.columns = ['location_name','industry_value_mean']
test = test.merge(industry_wheat_fortified, on = 'location_name')
test['diff'] = test.value_mean - test.industry_value_mean
test

,location_name,value_mean,industry_value_mean,diff
0,Ethiopia,0.000000,0.0,0.000000
1,India,6.300000,6.3,0.000000
2,Nigeria,17.452812,17.5,-0.047188
3,Bangladesh,0.155875,0.2,-0.044125
4,Pakistan,3.821239,3.8,0.021239
5,Uganda,8.500000,8.5,0.000000
6,United Republic of Tanzania,33.100000,33.1,0.000000
7,South Africa,5.707704,5.7,0.007704
8,Burkina Faso,17.389750,17.4,-0.010250
9,Kenya,27.095201,27.1,-0.004799
10,Myanmar,0.000000,0.0,0.000000
11,Nepal,7.334332,7.3,0.034332
12,Viet Nam,4.111875,4.1,0.011875
13,Cameroon,53.088564,6.4,46.688564
14,Democratic Republic of the Congo,0.000000,0.0,0.000000
15,Indonesia,73.100000,73.1,0.000000
16,Mozambique,12.632500,12.6,0.032500
17,Angola,16.888381,16.9,-0.011619
18,China,6.363472,10.3,-3.936528
19,Egypt,15.616431,15.6,0.016431
20,Ghana,17.121532,17.1,0.021532
21,Madagascar,8.630461,8.6,0.030461
22,Niger,30.000000,30.0,0.000000
23,Sudan,6.525113,6.5,0.025113

In [7]:
new_wheat = new_wheat['Baseline coverage']['Wheat flour\n(percent of population eating specified wheat flour)']['% fortifiable'].reset_index()

In [8]:
# # pull columns we're interested in
# rename_oil = {
#     ('Location', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2'): 'location_name',
#  'Fortifiable oil.1': 'percent of population eating industrially produced vehicle',
#  'Compliance % of fortifiable': 'percent of population eating fortified vehicle'
# }

# new_oil = new_oil.reset_index().rename(columns=rename_oil)

In [9]:
rename_wheat = {
    ('Location', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2'):'location_name',
    '% fortifiable':'percent of population eating industrially produced vehicle'
}

new_wheat = new_wheat.rename(columns=rename_wheat)

In [10]:
# reshape to our format
new_wheat = pd.melt(new_wheat, id_vars = 'location_name',
        value_vars = ['percent of population eating industrially produced vehicle'],
       var_name='value_description',value_name='value_mean')

In [11]:
#convert from prop to percent
new_wheat.value_mean = 100 * new_wheat.value_mean

In [12]:
new_wheat

,location_name,value_description,value_mean
0,Angola,percent of population eating industrially prod...,100.0
1,Bangladesh,percent of population eating industrially prod...,79.0
2,Burkina Faso,percent of population eating industrially prod...,100.0
3,CÃ´te d'Ivoire,percent of population eating industrially prod...,98.0
4,Cameroon,percent of population eating industrially prod...,80.0
5,China,percent of population eating industrially prod...,89.0
6,Democratic Republic of the Congo,percent of population eating industrially prod...,100.0
7,Egypt,percent of population eating industrially prod...,100.0
8,Ethiopia,percent of population eating industrially prod...,55.0
9,Ghana,percent of population eating industrially prod...,100.0
10,India,percent of population eating industrially prod...,30.0
11,Indonesia,percent of population eating industrially prod...,100.0
12,Kenya,percent of population eating industrially prod...,100.0
13,Madagascar,percent of population eating industrially prod...,100.0
14,Mozambique,percent of population eating industrially prod...,100.0
15,Myanmar,percent of population eating industrially prod...,100.0
16,Nepal,percent of population eating industrially prod...,25.0
17,Niger,percent of population eating industrially prod...,100.0
18,Nigeria,percent of population eating industrially prod...,100.0
19,Pakistan,percent of population eating industrially prod...,60.0
20,South Africa,percent of population eating industrially prod...,100.0
21,Sudan,percent of population eating industrially prod...,90.0
22,Uganda,percent of population eating industrially prod...,100.0
23,United Republic of Tanzania,percent of population eating industrially prod...,85.0
24,Viet Nam,percent of population eating industrially prod...,100.0

In [13]:
# fix c'ote divoire 
new_wheat.loc[new_wheat.location_name=="CÃ´te d'Ivoire","location_name"] = "Côte d'Ivoire"

In [14]:
# make sure we're not missing any locations / don't have any extra
assert(set(new_wheat.location_name).symmetric_difference(set(input_data.location_name))==set())

In [15]:
# formatting
new_wheat['vehicle'] = 'industry wheat'
new_wheat['nutrient'] = 'na'
new_wheat['u5_applicable'] = True
new_wheat['wra_applicable'] = True
new_wheat['sub_population'] = np.NaN
new_wheat['location_id'] = new_wheat.location_name.map(loc_id_map)

In [16]:
# grab pct fortified and use for industry wheat
fortified_wheat = input_data.loc[(input_data.vehicle=="wheat flour") & (input_data.value_description=="percent of population eating fortified vehicle")]
fortified_wheat['vehicle'] = "industry wheat"

/ihme/homes/beatrixh/.local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [17]:
new_wheat = new_wheat.append(fortified_wheat)

/ihme/code/central_comp/miniconda_svc-ccomp/envs/v108/lib/python3.7/site-packages/pandas/core/frame.py:7138: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

## oil

In [18]:
# pull in new numbers from Jonathan / industry
inputs_dir = "/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/inputs/"
new_oil = pd.read_excel(inputs_dir + "20210411_LSFF_input_data_for_IHME.xlsx", header = [1,2,3])

In [19]:
# subset to the oil numbers we're interested in
new_oil = new_oil.set_index(new_oil.columns[0])

new_oil = new_oil['Baseline coverage']['Oil\n(percent of population eating specified oil)'][['Fortifiable oil.1','Compliance % of fortifiable']]

In [20]:
# pull columns we're interested in
rename_oil = {
    ('Location', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2'): 'location_name',
 'Fortifiable oil.1': 'percent of population eating industrially produced vehicle',
 'Compliance % of fortifiable': 'percent of population eating fortified vehicle'
}

new_oil = new_oil.reset_index().rename(columns=rename_oil)

In [21]:
# reshape to our format
new_oil = pd.melt(new_oil, id_vars = 'location_name',
        value_vars = ['percent of population eating industrially produced vehicle',
       'percent of population eating fortified vehicle'],
       var_name='value_description',value_name='value_mean')

In [22]:
# fix c'ote divoire 
new_oil.loc[new_oil.location_name=="CÃ´te d'Ivoire","location_name"] = "Côte d'Ivoire"

In [23]:
# make sure we're not missing any locations / don't have any extra
assert(set(new_oil.location_name).symmetric_difference(set(input_data.location_name))==set())

In [24]:
# formatting
new_oil['vehicle'] = 'industry oil'
new_oil['nutrient'] = 'vitamin a'
new_oil['u5_applicable'] = True
new_oil['wra_applicable'] = True
new_oil['sub_population'] = np.NaN
new_oil['location_id'] = new_oil.location_name.map(loc_id_map)

In [25]:
# check formatting
new_oil.head()

,location_name,value_description,value_mean,vehicle,nutrient,u5_applicable,wra_applicable,sub_population,location_id
0,Angola,percent of population eating industrially prod...,72.320,industry oil,vitamin a,True,True,NaN,168
1,Bangladesh,percent of population eating industrially prod...,87.516,industry oil,vitamin a,True,True,NaN,161
2,Burkina Faso,percent of population eating industrially prod...,73.760,industry oil,vitamin a,True,True,NaN,201
3,Côte d'Ivoire,percent of population eating industrially prod...,72.000,industry oil,vitamin a,True,True,NaN,205
4,Cameroon,percent of population eating industrially prod...,72.000,industry oil,vitamin a,True,True,NaN,202

## add CIs

In [26]:
new_data = new_wheat.append(new_oil)

In [27]:
# from our (previously final) input sheet, select extracted rows of data (no regression or multiplicative results)
# then drop any rows duplicated for different nutrients
w_meta = w_meta[w_meta.estimation_status=='na'].drop(columns = 'nutrient').drop_duplicates()

In [28]:
# use ratio of scale over mean to estimate scale for new industry datapoints
w_meta['scale_over_mean'] = (w_meta.value_975_percentile - w_meta.value_025_percentile) / w_meta.value_mean
r = w_meta.loc[(w_meta.scale_over_mean!=np.inf) & (w_meta.scale_over_mean!=0),['vehicle','scale_over_mean']]

r_mean = r.scale_over_mean.mean()
r.loc[r.vehicle=="maize flour",'scale_over_mean'] = r_mean

r = r.groupby('vehicle').mean().dropna().rename(columns={'scale_over_mean':'r'}).reset_index()

In [29]:
vehicle_map = {'wheat flour':'industry wheat','oil':'industry oil'}
r.vehicle = r.vehicle.map(vehicle_map)

In [30]:
r

          vehicle         r
0             NaN  0.564982
1    industry oil  0.379944
2  industry wheat  0.688639

In [31]:
new_data = new_data.merge(r, on = 'vehicle', how = 'left')

In [32]:
# input estimated CIs
new_data['lower'] = np.clip(new_data.value_mean - (new_data.r * new_data.value_mean)/2, 0, 100)
new_data['upper'] = np.clip(new_data.value_mean + (new_data.r * new_data.value_mean)/2, 0, 100)


new_data.loc[(new_data.value_025_percentile.isna()),'value_025_percentile'] = new_data.lower
new_data.loc[(new_data.value_975_percentile.isna()),'value_975_percentile'] = new_data.upper

In [33]:
new_data = new_data.drop(columns=['lower','upper','r'])

In [34]:
output = input_data.append(new_data)[input_data.columns]

In [35]:
#checkout results
output.tail()

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
170,196,South Africa,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,3.0,2.430085,3.569915,True,True
171,522,Sudan,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.000000,0.000000,True,True
172,190,Uganda,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,54.4,44.065536,64.734464,True,True
173,189,United Republic of Tanzania,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,53.6,43.417513,63.782487,True,True
174,20,Viet Nam,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,70.0,56.701976,83.298024,True,True

In [36]:
output.columns

Index(['location_id', 'location_name', 'sub_population', 'vehicle',
       'value_description', 'nutrient', 'value_mean', 'value_025_percentile',
       'value_975_percentile', 'u5_applicable', 'wra_applicable'],
      dtype='object')

In [37]:
# checkout problem rows

In [38]:
output.loc[(output.value_mean > output.value_975_percentile) | (output.value_mean < output.value_025_percentile)]

Empty DataFrame
Columns: [location_id, location_name, sub_population, vehicle, value_description, nutrient, value_mean, value_025_percentile, value_975_percentile, u5_applicable, wra_applicable]
Index: []

In [39]:
output.loc[(output.value_mean == output.value_975_percentile) & (output.value_description!='percent of population eating vehicle')]

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
2,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
3,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
4,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
5,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
9,179,Ethiopia,NaN,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
...,...,...,...,...,...,...,...,...,...,...,...
87,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
88,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
165,15,Myanmar,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
166,164,Nepal,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
171,522,Sudan,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True

In [40]:
output.loc[(output.value_mean == output.value_025_percentile) & (output.value_description!='percent of population eating vehicle')]

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
2,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
3,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
4,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
5,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
9,179,Ethiopia,NaN,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
13,179,Ethiopia,NaN,wheat flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
14,179,Ethiopia,NaN,wheat flour,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
15,179,Ethiopia,NaN,wheat flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
16,179,Ethiopia,NaN,wheat flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
56,165,Pakistan,NaN,wheat flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
106,201,Burkina Faso,NaN,maize flour,percent of population eating industrially prod...,na,0.0,0.0,0.0,True,True
107,201,Burkina Faso,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
108,201,Burkina Faso,NaN,maize flour,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
109,201,Burkina Faso,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
110,201,Burkina Faso,NaN,maize flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
123,180,Kenya,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
125,180,Kenya,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
126,180,Kenya,NaN,maize flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
129,180,Kenya,NaN,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
138,15,Myanmar,total population,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,5.0,True,True
141,15,Myanmar,total population,wheat flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,5.0,True,True
142,15,Myanmar,total population,wheat flour,percent of population eating fortified vehicle,iron,0.0,0.0,5.0,True,True
143,15,Myanmar,NaN,wheat flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
144,15,Myanmar,total population,wheat flour,percent of population eating fortified vehicle,zinc,0.0,0.0,5.0,True,True
147,164,Nepal,NaN,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
153,164,Nepal,NaN,wheat flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
157,20,Viet Nam,NaN,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
192,205,Côte d'Ivoire,NaN,wheat flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
194,205,Côte d'Ivoire,NaN,wheat flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
195,205,Côte d'Ivoire,NaN,wheat flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
198,171,Democratic Republic of the Congo,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
199,171,Democratic Republic of the Congo,NaN,maize flour,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
200,171,Democratic Republic of the Congo,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
201,171,Democratic Republic of the Congo,NaN,maize flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
204,171,Democratic Republic of the Congo,NaN,oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
207,171,Democratic Republic of the Congo,NaN,wheat flour,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
208,171,Democratic Republic of the Congo,NaN,wheat flour,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
209,171,Democratic Republic of the Congo,NaN,wheat flour,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
210,171,Democratic Republic of the Congo,NaN,wheat flour,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
25,179,Ethiopia,NaN,industry wheat,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
26,179,Ethiopia,NaN,industry wheat,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
27,179,Ethiopia,NaN,industry wheat,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
28,179,Ethiopia,NaN,industry wheat,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
43,165,Pakistan,NaN,industry wheat,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
65,15,Myanmar,total population,industry wheat,percent of population eating fortified vehicle,folic acid,0.0,0.0,5.0,True,True
66,15,Myanmar,total population,industry wheat,percent of population eating fortified vehicle,iron,0.0,0.0,5.0,True,True
67,15,Myanmar,NaN,industry wheat,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
68,15,Myanmar,total population,industry wheat,percent of population eating fortified vehicle,zinc,0.0,0.0,5.0,True,True
72,164,Nepal,NaN,industry wheat,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
81,205,Côte d'Ivoire,NaN,industry wheat,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
83,205,Côte d'Ivoire,NaN,industry wheat,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
84,205,Côte d'Ivoire,NaN,industry wheat,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
85,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating fortified vehicle,folic acid,0.0,0.0,0.0,True,True
86,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating fortified vehicle,iron,0.0,0.0,0.0,True,True
87,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
88,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating fortified vehicle,zinc,0.0,0.0,0.0,True,True
165,15,Myanmar,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
166,164,Nepal,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True
171,522,Sudan,NaN,industry oil,percent of population eating fortified vehicle,vitamin a,0.0,0.0,0.0,True,True

In [41]:
output.loc[(output.value_025_percentile.isna()) | (output.value_975_percentile.isna())]

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
252,6,China,NaN,oil,percent of population eating fortified vehicle,vitamin a,NaN,NaN,NaN,True,True
267,141,Egypt,NaN,oil,percent of population eating fortified vehicle,vitamin a,NaN,NaN,NaN,True,True

In [42]:
input_data.loc[(input_data.value_025_percentile.isna()) | (input_data.value_975_percentile.isna())]

,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
252,6,China,NaN,oil,percent of population eating fortified vehicle,vitamin a,NaN,NaN,NaN,True,True
267,141,Egypt,NaN,oil,percent of population eating fortified vehicle,vitamin a,NaN,NaN,NaN,True,True

In [43]:
output.to_csv('/ihme/homes/beatrixh/repos/scratch/lsff_input_coverage_data_w_industry_oil_wheat_v2_04_14_2021.csv')

In [44]:
save_path = '/ihme/homes/beatrixh/vivarium_research_lsff/data_prep/outputs/lsff_input_coverage_data_w_industry_oil_wheat_v2_04_14_2021.csv'
output.to_csv(save_path)