In [1]:
import pandas as pd, numpy as np
from tqdm import tqdm

import data_processing
import lbwsg_boe
import iron_bw_calc_industry
# import lbwsg
# import lsff_interventions
# import demography

!date
!whoami
!pwd

Thu Apr 15 14:20:46 PDT 2021
ndbs
/ihme/homes/ndbs/vivarium_research_lsff/nanosim_models

In [2]:
%load_ext autoreload
%autoreload 2

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

# Test reading input data with path for industry coverage specified

In [3]:
!ls results_industry/

11_parallel.txt
141_parallel.txt
15_parallel.txt
161_parallel.txt
163_parallel.txt
164_parallel.txt
165_parallel.txt
168_parallel.txt
171_parallel.txt
179_parallel.txt
180_parallel.txt
181_parallel.txt
184_parallel.txt
189_parallel.txt
190_parallel.txt
196_parallel.txt
201_parallel.txt
202_parallel.txt
205_parallel.txt
207_parallel.txt
20_parallel.txt
213_parallel.txt
214_parallel.txt
522_parallel.txt
6_parallel.txt
iron_bw_results__Bangladesh_161.csv
iron_bw_results__Egypt_141.csv
iron_bw_results__Ghana_207.csv
iron_bw_results__India_163.csv
iron_bw_results__Kenya_180.csv
iron_bw_results__South Africa_196.csv
iron_bw_results__United Republic of Tanzania_189.csv
lsff_input_coverage_data_w_industry_oil_wheat_v3_04_14_2021.csv
lsff_input_coverage_data_w_industry_oil_wheat_v4_04_15_2021.csv

In [4]:
input_data = data_processing.get_fortification_input_data(
    coverage_data_path='results_industry/lsff_input_coverage_data_w_industry_oil_wheat_v4_04_15_2021.csv',
)
input_data.coverage.head()

,Unnamed: 0,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
0,0,179,Ethiopia,NaN,maize flour,percent of population eating vehicle,na,59.263848,24.950317,93.577380,True,True
1,1,179,Ethiopia,NaN,maize flour,percent of population eating industrially prod...,na,27.167514,11.437632,42.897396,True,True
2,2,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,folic acid,0.000020,0.000010,0.000030,True,True
3,3,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,iron,0.000020,0.000010,0.000030,True,True
4,4,179,Ethiopia,NaN,maize flour,percent of population eating fortified vehicle,vitamin a,0.000020,0.000010,0.000030,True,True

In [5]:
input_data.coverage.vehicle.unique()

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['maize flour', 'oil', 'wheat flour', 'industry wheat',
       'industry oil'], dtype=object)

# Time the model run with 10,000 simulants and 10 draws, using location name

In [6]:
%%time
iron_bw_calc_industry.main(
    '/ihme/homes/ndbs/vivarium_research_lsff',
    'temp',
    'Cameroon',
    10_000,
    10,
    random_seed=3456,
    take_mean=False
)
!ls temp/

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/tables/atom.py:1224: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return pickle.loads(array.tostring())

163_parallel.txt       iron_bw_results__Cameroon_202.csv
207_parallel.txt       iron_bw_results__Ghana_207.csv
Cameroon_parallel.txt  iron_bw_results__India_163.csv
CPU times: user 15.8 s, sys: 1.03 s, total: 16.9 s
Wall time: 17.4 s

## Now test passing location id instead of location name

Looks like I re-ran the notebook, so location 163 already existed above but didn't when I first ran this cell:

In [7]:
%%time
iron_bw_calc_industry.main(
    '/ihme/homes/ndbs/vivarium_research_lsff',
    'temp',
    163,
    10_000,
    10,
    random_seed=3456,
    take_mean=False
)
!ls temp/

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/tables/atom.py:1224: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return pickle.loads(array.tostring())

163_parallel.txt       iron_bw_results__Cameroon_202.csv
207_parallel.txt       iron_bw_results__Ghana_207.csv
Cameroon_parallel.txt  iron_bw_results__India_163.csv
CPU times: user 15.6 s, sys: 751 ms, total: 16.4 s
Wall time: 16.6 s

In [8]:
cameroon = pd.read_csv('temp/iron_bw_results__Cameroon_202.csv')
cameroon

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,location_id,vehicle,coverage_level,measure,age_group_id,draw_43,draw_67,draw_240,draw_298,draw_314,draw_539,draw_558,draw_709,draw_737,draw_767
0,202,industry wheat,0.2,pif,2,0.000598,0.000361,0.000231,0.000209,0.000636,0.000085,0.000146,0.001334,0.000229,0.000298
1,202,industry wheat,0.2,pif,3,0.000669,0.000576,0.000442,0.000257,0.000689,0.000127,0.000131,0.001223,0.000346,0.000512
2,202,industry wheat,0.2,averted_dalys,2,676.344414,469.866471,232.436825,276.095093,565.027201,98.277022,199.331916,1467.575452,207.032007,328.793961
3,202,industry wheat,0.2,averted_dalys,3,165.423452,174.815051,89.251195,66.895314,164.726813,28.368268,23.868203,301.986555,60.023256,102.841048
4,202,industry wheat,0.5,pif,2,0.000705,0.000452,0.000302,0.000242,0.000899,0.000096,0.000165,0.001884,0.000300,0.000361
5,202,industry wheat,0.5,pif,3,0.000772,0.000646,0.000472,0.000297,0.000850,0.000154,0.000155,0.001489,0.000396,0.000593
6,202,industry wheat,0.5,averted_dalys,2,793.576596,579.423044,313.748769,316.911607,804.328464,109.633155,225.348108,2102.014914,270.979974,404.335548
7,202,industry wheat,0.5,averted_dalys,3,190.099205,196.175578,94.408242,77.658097,198.385026,34.591839,30.417996,373.626783,68.139723,118.707300
8,202,industry wheat,0.8,pif,2,0.000927,0.000584,0.000324,0.000282,0.001197,0.000142,0.000173,0.002148,0.000458,0.000553
9,202,industry wheat,0.8,pif,3,0.000901,0.000749,0.000580,0.000364,0.001005,0.000211,0.000169,0.001708,0.000447,0.000723
10,202,industry wheat,0.8,averted_dalys,2,1017.915543,747.914487,336.494424,369.844780,1070.454147,156.070022,236.643763,2414.601781,431.497479,604.690067
11,202,industry wheat,0.8,averted_dalys,3,220.520833,223.750069,116.202046,95.058218,235.862381,48.706898,34.659410,419.999977,76.936716,145.499366

In [9]:
india = pd.read_csv('temp/iron_bw_results__India_163.csv')
india

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,location_id,vehicle,coverage_level,measure,age_group_id,draw_43,draw_67,draw_240,draw_298,draw_314,draw_539,draw_558,draw_709,draw_737,draw_767
0,163,industry wheat,0.2,pif,2,0.000805,0.001070,0.000616,0.000626,0.001087,0.000699,0.000823,0.001328,0.000374,0.000481
1,163,industry wheat,0.2,pif,3,0.000746,0.001020,0.000643,0.000561,0.000774,0.000542,0.000694,0.001292,0.000324,0.000416
2,163,industry wheat,0.2,averted_dalys,2,24854.007712,39335.433126,18474.879659,22371.255710,29582.096093,21245.587830,32065.262893,46894.736717,13221.003708,15511.161492
3,163,industry wheat,0.2,averted_dalys,3,4439.267516,7075.379287,3634.387699,3795.224569,4139.625161,3150.968933,5195.648517,8953.512083,2201.240516,2639.820559
4,163,industry wheat,0.5,pif,2,0.000972,0.001289,0.000808,0.000734,0.001285,0.000820,0.000976,0.001635,0.000462,0.000640
5,163,industry wheat,0.5,pif,3,0.000947,0.001284,0.000761,0.000702,0.001033,0.000695,0.000890,0.001590,0.000377,0.000493
6,163,industry wheat,0.5,averted_dalys,2,30113.536815,47196.487326,24434.876376,26365.444568,34854.693807,24879.346401,38069.039689,57638.182586,16348.482113,20773.172034
7,163,industry wheat,0.5,averted_dalys,3,5634.245016,8905.529555,4307.751980,4761.977551,5474.616031,4021.583312,6672.303304,11030.677426,2556.847547,3124.397645
8,163,industry wheat,0.8,pif,2,0.001190,0.001542,0.001094,0.000887,0.001522,0.000972,0.001141,0.002018,0.000540,0.000716
9,163,industry wheat,0.8,pif,3,0.001127,0.001526,0.000854,0.000828,0.001251,0.000846,0.001108,0.001965,0.000471,0.000608
10,163,industry wheat,0.8,averted_dalys,2,36776.048554,56654.369319,33353.504878,31323.752050,41156.808527,29650.640767,44471.745403,71214.621907,19086.176528,23205.035367
11,163,industry wheat,0.8,averted_dalys,3,6690.483469,10572.961322,4824.844379,5599.069590,6628.972797,4875.597225,8219.966746,13617.776441,3174.937274,3850.978194

# Check that the input data looks good

In [10]:
input_data.consumption.head()

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,location_id,sub_population,vehicle,metric,mass_unit,time_unit,pop_denom,value_mean_gday,lower,upper,location_name,value_mean_coverage,value_025_percentile,value_975_percentile
0,163,total population,wheat flour,mean,g,day,capita,169.62,113.134860,226.105140,India,83.200000,79.500000,86.500000
1,179,total population,maize flour,mean,g,day,capita,113.84,68.762191,158.917809,Ethiopia,59.263848,24.950317,93.577380
2,179,total population,wheat flour,mean,g,day,capita,97.64,65.124913,130.155087,Ethiopia,28.000000,13.776168,42.223832
3,214,total population,maize flour,mean,g,day,capita,95.10,57.442765,132.757235,Nigeria,57.415462,54.867114,60.033478
4,214,total population,wheat flour,mean,g,day,capita,49.15,32.782563,65.517437,Nigeria,62.759594,60.359594,65.129264

In [12]:
input_data.consumption.query("vehicle=='industry wheat'").shape

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(25, 14)

In [14]:
input_data.coverage.query("vehicle=='industry wheat'").shape

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(125, 12)

In [17]:
input_data.coverage.query("vehicle=='industry wheat' and nutrient in ['na', 'iron']").shape

/ihme/homes/ndbs/miniconda3/envs/lsff-iron-38/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(50, 12)

In [18]:
input_data.coverage.query("vehicle=='industry wheat' and nutrient in ['na', 'iron']").head(10)

,Unnamed: 0,location_id,location_name,sub_population,vehicle,value_description,nutrient,value_mean,value_025_percentile,value_975_percentile,u5_applicable,wra_applicable
309,0,168,Angola,NaN,industry wheat,percent of population eating industrially prod...,na,27.200,17.834510,36.565490,True,True
310,1,161,Bangladesh,NaN,industry wheat,percent of population eating industrially prod...,na,33.101,21.703681,44.498319,True,True
311,2,201,Burkina Faso,NaN,industry wheat,percent of population eating industrially prod...,na,48.000,31.472665,64.527335,True,True
312,3,205,Côte d'Ivoire,NaN,industry wheat,percent of population eating industrially prod...,na,90.160,59.116156,99.999990,True,True
313,4,202,Cameroon,NaN,industry wheat,percent of population eating industrially prod...,na,65.440,42.907733,87.972267,True,True
314,5,6,China,NaN,industry wheat,percent of population eating industrially prod...,na,48.683,31.920495,65.445505,True,True
315,6,171,Democratic Republic of the Congo,NaN,industry wheat,percent of population eating industrially prod...,na,0.600,0.393408,0.806592,True,True
316,7,141,Egypt,NaN,industry wheat,percent of population eating industrially prod...,na,88.500,58.027726,99.999990,True,True
317,8,179,Ethiopia,NaN,industry wheat,percent of population eating industrially prod...,na,15.400,10.097480,20.702520,True,True
318,9,207,Ghana,NaN,industry wheat,percent of population eating industrially prod...,na,82.700,54.224779,99.999990,True,True